### ISSUE TITLE
Swap out satori/go.uuid for gofrs/uuid

### ISSUE THREAD

**Issue by jakebailey** [src-d/go-kallax#286]
The satori UUID library isn't being maintained, and has a number of major issues with generating random UUIDs in the latest iteration. It'd be a good idea to swap it out for https://github.com/gofrs/uuid, which should be a drop-in community-maintained replacement without the bugs.

I currently have this in my `Gopkg.toml` to hack it in my projects for now:

```toml
[[constraint]]
  name = "github.com/satori/go.uuid"
  source = "https://github.com/gofrs/uuid.git"
```
